<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatProductSeeder extends Seeder
{
    /**
     * Run the database seeds for CAT products
     */
    public function run(): void
    {
        // Obtener las categorías de gatos
        $catAlimentoSecoGatos = Category::where('slug', 'alimento-seco-gatos')->first()?->id;
        $catAlimentoHumedoGatos = Category::where('slug', 'alimento-humedo-gatos')->first()?->id;
        $catSnacksGatos = Category::where('slug', 'snacks-gatos')->first()?->id;
        $catJuguetesGatos = Category::where('slug', 'juguetes-gatos')->first()?->id;
        $catRascadores = Category::where('slug', 'rascadores-gatos')->first()?->id;
        $catCamasGatos = Category::where('slug', 'camas-gatos')->first()?->id;
        $catComederosGatos = Category::where('slug', 'comederos-gatos')->first()?->id;
        $catArena = Category::where('slug', 'arena-gatos')->first()?->id;
        $catAreneros = Category::where('slug', 'areneros-gatos')->first()?->id;

        // Productos para GATOS
        $productos = [
            // ALIMENTO SECO PARA GATOS (3 productos)
            [
                'category_id' => $catAlimentoSecoGatos,
                'name' => 'Alimento Premium para Gatos Adultos',
                'slug' => 'alimento-premium-gatos-adultos',
                'description' => 'Alimento balanceado para gatos adultos con ingredientes naturales',
                'long_description' => 'Alimento completo y balanceado para gatos adultos de 1 a 7 años. Con pollo real, taurina para la salud del corazón y la visión, omega 3 y 6 para piel y pelaje saludables. Bolsa de 3kg.',
                'price' => 85000.00,
                'sale_price' => 75000.00,
                'sku' => 'FOOD-CAT-001',
                'stock' => 40,
                'brand' => 'Royal Pet',
                'weight' => 3.00,
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'Alimento Premium para Gatos Adultos',
                'meta_description' => 'Nutrición completa para gatos adultos',
                'meta_keywords' => 'alimento gatos, comida gatos, premium',
            ],
            [
                'category_id' => $catAlimentoSecoGatos,
                'name' => 'Alimento para Gatitos (Kitten)',
                'slug' => 'alimento-gatitos-kitten',
                'description' => 'Fórmula especial para gatitos de 2 meses a 1 año',
                'long_description' => 'Alimento formulado para gatitos en crecimiento. Rico en proteínas, DHA para desarrollo cerebral, calcio para huesos fuertes. Bolsa de 1.5kg.',
                'price' => 55000.00,
                'sale_price' => null,
                'sku' => 'FOOD-CAT-002',
                'stock' => 30,
                'brand' => 'Nutricat',
                'weight' => 1.50,
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'Alimento para Gatitos Kitten',
                'meta_description' => 'Nutrición completa para gatitos en crecimiento',
                'meta_keywords' => 'alimento gatitos, kitten, cachorros gato',
            ],
            [
                'category_id' => $catAlimentoSecoGatos,
                'name' => 'Alimento para Gatos Esterilizados',
                'slug' => 'alimento-gatos-esterilizados',
                'description' => 'Control de peso para gatos castrados o esterilizados',
                'long_description' => 'Alimento bajo en grasas, alto en fibra para control de peso. Con L-carnitina para metabolismo saludable. Ideal para gatos esterilizados que tienden al sobrepeso. Bolsa de 3kg.',
                'price' => 95000.00,
                'sale_price' => null,
                'sku' => 'FOOD-CAT-003',
                'stock' => 35,
                'brand' => 'FitCat',
                'weight' => 3.00,
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Alimento para Gatos Esterilizados',
                'meta_description' => 'Control de peso para gatos castrados',
                'meta_keywords' => 'alimento esterilizados, gatos castrados, control peso',
            ],

            // ALIMENTO HÚMEDO PARA GATOS (3 productos)
            [
                'category_id' => $catAlimentoHumedoGatos,
                'name' => 'Paté de Atún para Gatos',
                'slug' => 'pate-atun-gatos',
                'description' => 'Delicioso paté de atún natural',
                'long_description' => 'Paté premium elaborado con atún real y caldo nutritivo. Alto contenido de proteína, sin conservantes artificiales. Lata de 85g.',
                'price' => 8000.00,
                'sale_price' => null,
                'sku' => 'FOOD-CAT-WET-001',
                'stock' => 120,
                'brand' => 'Whiskas',
                'weight' => 0.085,
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Paté de Atún para Gatos',
                'meta_description' => 'Delicioso paté de atún natural en lata',
                'meta_keywords' => 'pate gatos, comida humeda, atun',
            ],
            [
                'category_id' => $catAlimentoHumedoGatos,
                'name' => 'Pouch de Pollo y Salmón',
                'slug' => 'pouch-pollo-salmon-gatos',
                'description' => 'Pouch con pollo y salmón en salsa',
                'long_description' => 'Deliciosa mezcla de pollo y salmón en salsa gourmet. Textura suave en trozos. Bolsita de 85g.',
                'price' => 9000.00,
                'sale_price' => 7500.00,
                'sku' => 'FOOD-CAT-WET-002',
                'stock' => 100,
                'brand' => 'Felix',
                'weight' => 0.085,
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'Pouch Pollo y Salmón para Gatos',
                'meta_description' => 'Delicioso pouch con pollo y salmón',
                'meta_keywords' => 'pouch gatos, comida humeda, pollo salmon',
            ],
            [
                'category_id' => $catAlimentoHumedoGatos,
                'name' => 'Paté de Hígado Premium',
                'slug' => 'pate-higado-gatos',
                'description' => 'Paté gourmet de hígado',
                'long_description' => 'Paté suave de hígado con textura irresistible. Rico en vitaminas del complejo B. Lata de 85g.',
                'price' => 8500.00,
                'sale_price' => null,
                'sku' => 'FOOD-CAT-WET-003',
                'stock' => 90,
                'brand' => 'Gourmet',
                'weight' => 0.085,
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Paté de Hígado para Gatos',
                'meta_description' => 'Paté gourmet de hígado premium',
                'meta_keywords' => 'pate gatos, higado, gourmet',
            ],

            // SNACKS PARA GATOS (3 productos)
            [
                'category_id' => $catSnacksGatos,
                'name' => 'Treats de Pollo Deshidratado',
                'slug' => 'treats-pollo-deshidratado-gatos',
                'description' => 'Snacks de pollo 100% natural deshidratado',
                'long_description' => 'Deliciosos treats elaborados con pechuga de pollo deshidratada. Sin conservantes ni colorantes artificiales. Bolsa de 50g.',
                'price' => 15000.00,
                'sale_price' => null,
                'sku' => 'SNACK-CAT-001',
                'stock' => 80,
                'brand' => 'Natural Choice',
                'weight' => 0.05,
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Treats de Pollo Deshidratado',
                'meta_description' => 'Snacks naturales de pollo para gatos',
                'meta_keywords' => 'treats gatos, pollo, snacks',
            ],
            [
                'category_id' => $catSnacksGatos,
                'name' => 'Snacks Anti-Hairball',
                'slug' => 'snacks-anti-hairball-gatos',
                'description' => 'Snacks que ayudan a prevenir bolas de pelo',
                'long_description' => 'Deliciosos snacks con malta y fibra que ayudan a prevenir la formación de bolas de pelo. Con vitaminas y taurina. Bolsa de 60g.',
                'price' => 18000.00,
                'sale_price' => 15000.00,
                'sku' => 'SNACK-CAT-002',
                'stock' => 70,
                'brand' => 'Catsan',
                'weight' => 0.06,
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'Snacks Anti-Hairball para Gatos',
                'meta_description' => 'Previene bolas de pelo en gatos',
                'meta_keywords' => 'snacks gatos, hairball, malta',
            ],
            [
                'category_id' => $catSnacksGatos,
                'name' => 'Palitos de Salmón',
                'slug' => 'palitos-salmon-gatos',
                'description' => 'Palitos crujientes con sabor a salmón',
                'long_description' => 'Palitos crujientes elaborados con salmón real. Rico en omega 3 para pelaje brillante. Pack de 5 palitos individuales.',
                'price' => 12000.00,
                'sale_price' => null,
                'sku' => 'SNACK-CAT-003',
                'stock' => 95,
                'brand' => 'Dreamies',
                'weight' => 0.04,
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Palitos de Salmón para Gatos',
                'meta_description' => 'Palitos crujientes con salmón real',
                'meta_keywords' => 'palitos gatos, salmon, snacks',
            ],

            // JUGUETES PARA GATOS (3 productos)
            [
                'category_id' => $catJuguetesGatos,
                'name' => 'Varita con Plumas',
                'slug' => 'varita-plumas-gatos',
                'description' => 'Varita interactiva con plumas coloridas',
                'long_description' => 'Juguete interactivo con varita extensible y plumas naturales. Estimula el instinto cazador. Vara de 40cm extensible.',
                'price' => 25000.00,
                'sale_price' => null,
                'sku' => 'TOY-CAT-001',
                'stock' => 50,
                'brand' => 'PetPlay',
                'weight' => 0.10,
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'Varita con Plumas para Gatos',
                'meta_description' => 'Juguete interactivo con plumas',
                'meta_keywords' => 'juguete gatos, varita, plumas',
            ],
            [
                'category_id' => $catJuguetesGatos,
                'name' => 'Ratón con Catnip',
                'slug' => 'raton-catnip-gatos',
                'description' => 'Ratón de felpa relleno de catnip',
                'long_description' => 'Ratón de felpa suave relleno de catnip natural premium. Estimula el juego activo. Tamaño 10cm.',
                'price' => 12000.00,
                'sale_price' => 10000.00,
                'sku' => 'TOY-CAT-002',
                'stock' => 85,
                'brand' => 'Kong',
                'weight' => 0.05,
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Ratón con Catnip para Gatos',
                'meta_description' => 'Ratón de felpa con catnip natural',
                'meta_keywords' => 'juguete gatos, raton, catnip',
            ],
            [
                'category_id' => $catJuguetesGatos,
                'name' => 'Pelota Sonajero Interactiva',
                'slug' => 'pelota-sonajero-gatos',
                'description' => 'Pelota con cascabel que suena al rodar',
                'long_description' => 'Pelota ligera con cascabel interno que estimula la caza. Material seguro y resistente. Diámetro 5cm. Pack de 3 unidades.',
                'price' => 18000.00,
                'sale_price' => null,
                'sku' => 'TOY-CAT-003',
                'stock' => 60,
                'brand' => 'CatPlay',
                'weight' => 0.08,
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Pelota Sonajero para Gatos',
                'meta_description' => 'Pelota interactiva con cascabel',
                'meta_keywords' => 'juguete gatos, pelota, sonajero',
            ],

            // RASCADORES PARA GATOS (2 productos)
            [
                'category_id' => $catRascadores,
                'name' => 'Rascador Torre Mediano',
                'slug' => 'rascador-torre-mediano-gatos',
                'description' => 'Torre rascadora de 80cm con plataformas',
                'long_description' => 'Torre rascadora con dos plataformas, poste recubierto de sisal y hamaca superior. Base estable. Altura 80cm.',
                'price' => 180000.00,
                'sale_price' => 150000.00,
                'sku' => 'SCRA-CAT-001',
                'stock' => 15,
                'brand' => 'FelixTower',
                'weight' => 8.00,
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'Rascador Torre Mediano para Gatos',
                'meta_description' => 'Torre rascadora con plataformas',
                'meta_keywords' => 'rascador gatos, torre, sisal',
            ],
            [
                'category_id' => $catRascadores,
                'name' => 'Rascador de Pared',
                'slug' => 'rascador-pared-gatos',
                'description' => 'Rascador de sisal para montar en pared',
                'long_description' => 'Rascador vertical de sisal natural para montar en pared. Ahorra espacio y protege tus muebles. Medidas: 60x30cm.',
                'price' => 45000.00,
                'sale_price' => null,
                'sku' => 'SCRA-CAT-002',
                'stock' => 25,
                'brand' => 'WallCat',
                'weight' => 2.00,
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Rascador de Pared para Gatos',
                'meta_description' => 'Rascador vertical de sisal',
                'meta_keywords' => 'rascador gatos, pared, sisal',
            ],

            // CAMAS PARA GATOS (2 productos)
            [
                'category_id' => $catCamasGatos,
                'name' => 'Cama Cueva Acolchada',
                'slug' => 'cama-cueva-acolchada-gatos',
                'description' => 'Cama tipo cueva suave y cálida',
                'long_description' => 'Cama en forma de cueva con interior acolchado. Tu gato se sentirá seguro y cómodo. Lavable a máquina. Medidas: 40x40x35cm.',
                'price' => 65000.00,
                'sale_price' => 55000.00,
                'sku' => 'BED-CAT-001',
                'stock' => 30,
                'brand' => 'CozyPet',
                'weight' => 1.20,
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'Cama Cueva Acolchada para Gatos',
                'meta_description' => 'Cama tipo cueva suave y cálida',
                'meta_keywords' => 'cama gatos, cueva, acolchada',
            ],
            [
                'category_id' => $catCamasGatos,
                'name' => 'Hamaca para Ventana',
                'slug' => 'hamaca-ventana-gatos',
                'description' => 'Hamaca que se adhiere a la ventana con ventosas',
                'long_description' => 'Hamaca con ventosas ultra fuertes que se adhieren a cualquier ventana. Tu gato podrá disfrutar del sol. Soporta hasta 15kg.',
                'price' => 48000.00,
                'sale_price' => null,
                'sku' => 'BED-CAT-002',
                'stock' => 20,
                'brand' => 'SunnyC at',
                'weight' => 0.80,
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Hamaca para Ventana para Gatos',
                'meta_description' => 'Hamaca con ventosas para ventana',
                'meta_keywords' => 'hamaca gatos, ventana, ventosas',
            ],

            // COMEDEROS Y BEBEDEROS (2 productos)
            [
                'category_id' => $catComederosGatos,
                'name' => 'Comedero Doble Antideslizante',
                'slug' => 'comedero-doble-gatos',
                'description' => 'Comedero doble de acero inoxidable',
                'long_description' => 'Set de comedero y bebedero en acero inoxidable con base antideslizante. Fácil de limpiar, higiénico y duradero. Capacidad: 300ml cada uno.',
                'price' => 35000.00,
                'sale_price' => null,
                'sku' => 'BOWL-CAT-001',
                'stock' => 45,
                'brand' => 'PetDinner',
                'weight' => 0.60,
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Comedero Doble para Gatos',
                'meta_description' => 'Comedero de acero inoxidable',
                'meta_keywords' => 'comedero gatos, acero, doble',
            ],
            [
                'category_id' => $catComederosGatos,
                'name' => 'Fuente de Agua Automática',
                'slug' => 'fuente-agua-automatica-gatos',
                'description' => 'Fuente con agua en movimiento para gatos',
                'long_description' => 'Fuente eléctrica con filtro de carbón que mantiene el agua fresca y oxigenada. Estimula a los gatos a beber más agua. Capacidad: 2L.',
                'price' => 95000.00,
                'sale_price' => 85000.00,
                'sku' => 'BOWL-CAT-002',
                'stock' => 18,
                'brand' => 'Catit',
                'weight' => 1.50,
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'Fuente de Agua Automática para Gatos',
                'meta_description' => 'Fuente eléctrica con agua en movimiento',
                'meta_keywords' => 'fuente gatos, agua automatica, bebedero',
            ],

            // ARENA SANITARIA (2 productos)
            [
                'category_id' => $catArena,
                'name' => 'Arena Aglutinante Premium',
                'slug' => 'arena-aglutinante-gatos',
                'description' => 'Arena aglutinante con control de olores',
                'long_description' => 'Arena de arcilla bentonita aglutinante. Forma grumos sólidos para fácil limpieza. Con bicarbonato para control de olores. Saco de 10kg.',
                'price' => 45000.00,
                'sale_price' => 40000.00,
                'sku' => 'LITT-CAT-001',
                'stock' => 60,
                'brand' => 'CatSan',
                'weight' => 10.00,
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'Arena Aglutinante Premium para Gatos',
                'meta_description' => 'Arena aglutinante con control de olores',
                'meta_keywords' => 'arena gatos, aglutinante, control olores',
            ],
            [
                'category_id' => $catArena,
                'name' => 'Arena de Sílica Gel',
                'slug' => 'arena-silica-gel-gatos',
                'description' => 'Arena de cristales de sílica súper absorbente',
                'long_description' => 'Arena de cristales de sílica que absorbe líquidos y olores inmediatamente. Dura hasta 1 mes para un gato. Sin polvo. Bolsa de 3.8L.',
                'price' => 55000.00,
                'sale_price' => null,
                'sku' => 'LITT-CAT-002',
                'stock' => 40,
                'brand' => 'Crystal Clear',
                'weight' => 3.80,
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Arena de Sílica Gel para Gatos',
                'meta_description' => 'Arena de cristales súper absorbente',
                'meta_keywords' => 'arena gatos, silica, cristales',
            ],

            // ARENEROS (2 productos)
            [
                'category_id' => $catAreneros,
                'name' => 'Arenero Cubierto Grande',
                'slug' => 'arenero-cubierto-grande-gatos',
                'description' => 'Arenero cerrado con puerta y filtro',
                'long_description' => 'Arenero cubierto con puerta abatible, filtro de carbón en tapa y bandeja extraíble. Controla olores y dispersión de arena. Medidas: 50x40x40cm.',
                'price' => 85000.00,
                'sale_price' => null,
                'sku' => 'BOX-CAT-001',
                'stock' => 25,
                'brand' => 'ModkoBox',
                'weight' => 3.00,
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'Arenero Cubierto Grande para Gatos',
                'meta_description' => 'Arenero cerrado con filtro y puerta',
                'meta_keywords' => 'arenero gatos, cubierto, grande',
            ],
            [
                'category_id' => $catAreneros,
                'name' => 'Arenero Abierto con Pala',
                'slug' => 'arenero-abierto-pala-gatos',
                'description' => 'Arenero abierto básico con bordes altos',
                'long_description' => 'Arenero abierto con bordes altos que evitan derrames. Incluye pala. Fácil de limpiar. Medidas: 45x35x15cm.',
                'price' => 35000.00,
                'sale_price' => 30000.00,
                'sku' => 'BOX-CAT-002',
                'stock' => 40,
                'brand' => 'BasicCat',
                'weight' => 1.20,
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Arenero Abierto con Pala para Gatos',
                'meta_description' => 'Arenero abierto básico con pala',
                'meta_keywords' => 'arenero gatos, abierto, pala',
            ],
        ];

        // Insertar productos
        foreach ($productos as $producto) {
            $productId = DB::table('products')->insertGetId(array_merge($producto, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));

            // Agregar una imagen placeholder para cada producto
            DB::table('product_images')->insert([
                'product_id' => $productId,
                'image_url' => 'https://via.placeholder.com/500x500.png?text=' . urlencode($producto['name']),
                'is_primary' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->command->info('✅ Productos de GATOS creados exitosamente: ' . count($productos) . ' productos');
    }
}
